### PR TITLE
Add some Files

### PR DESCRIPTION
**Pull request by liu412825long**
1 : I have been the .html files rename to .jsp.
2 : The Dao and Service has finished. And Regist and Login  are
successful . but I found The Struts Tags is not used.

### CODE REVIEW

**Comment by shengqianghu** [comment]
the struts tags are not working?

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Yes,If you use the struts tags ,the JSP page has exception.So I think the struts tags's jar is not exist. but I don't know where it is.

**Comment by liu412825long** [comment]
Do you copy?

**Pull request merged**
